
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: bueiro_backend
    env_file:
      - ./.env
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      PORT: "8080"
      PROJECT__NAME: "${PROJECT__NAME}"
      VERSION: "${VERSION}"
      API__STR: "${API__STR}"
      SECRET__KEY: "${SECRET__KEY}"
      ALGORITHM: "${ALGORITHM}"
      ACCESS__TOKEN__EXPIRE__MINUTES: "${ACCESS__TOKEN__EXPIRE__MINUTES}"
      HARDWARE__TOKEN: "${HARDWARE__TOKEN}"
      REDIS_URL_LOCAL: "redis://redis:6379/0"
      REDIS_LOCAL: "true"
      DB__LOCAL: "true"
      DATABASE__URL__CLOUD: "${DATABASE__URL__CLOUD}"
      DATABASE__URL__LOCAL: "postgresql+asyncpg://bueiro_user:bueiro_password@db:5432/bueiro_db"
      MIGRATIONS_URL_LOCAL: "postgresql+psycopg2://bueiro_user:bueiro_password@db:5432/bueiro_db"
      GOOGLE_CLIENT_ID: "${GOOGLE__CLIENT__ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE__CLIENT__SECRET}"
      GOOGLE_FRONTEND_REDIRECT_URL: "${GOOGLE__FRONTEND__REDIRECT__URL}"
      ROWS__API__KEY: "${ROWS__API__KEY}"
      ROWS__BASE__URL: "${ROWS__BASE__URL}"
      ROWS__SPREADSHEET__ID: "${ROWS__SPREADSHEET__ID}"
      ROWS__TABLE__ID: "${ROWS__TABLE__ID}"
      ALLOWED__ORIGINS: "${ALLOWED__ORIGINS}"
      DOTNET__SYSTEM__GLOBALIZATION__INVARIANT: "${DOTNET__SYSTEM__GLOBALIZATION__INVARIANT}"
      APP__ID__SECRET: "${APP__ID__SECRET}"
      ALLOWED__HOSTS: "${ALLOWED__HOSTS}"
      EMAIL__USERS__ADMIN: "${EMAIL__USERS__ADMIN}"
      LOG__DIRECTORY: "/app/log"
    volumes:
      - ./.env:/app/.env:ro
      - ./log:/app/log
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - bueiro_net
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: bueiro_db
    environment:
      POSTGRES_USER: "bueiro_user"
      POSTGRES_PASSWORD: "bueiro_password"
      POSTGRES_DB: "bueiro_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bueiro_net

  redis:
    image: redis:7-alpine
    container_name: bueiro_redis
    ports:
      - "6379:6379"
    networks:
      - bueiro_net

networks:
  bueiro_net:
    driver: bridge

volumes:
  postgres_data: