"""add_role_model_and_user_relation

Revision ID: 7569d6662006
Revises: 7addfd20b66b
Create Date: 2026-04-03 13:34:44.919391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.features.auth.models import Role

# revision identifiers, used by Alembic.
revision: str = '7569d6662006'
down_revision: Union[str, Sequence[str], None] = '7addfd20b66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Cria a tabela
    roles_table = op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    
    # 2. Insere os registros iniciais (seeds)
    op.bulk_insert(roles_table,
        [
            {'id': 1, 'name': 'Admin', 'description': 'Acesso total administrativo.'},
            {'id': 2, 'name': 'Manager', 'description': 'Gestor do sistema, com permissões elevadas.'},
            {'id': 3, 'name': 'User', 'description': 'Usuário comum com acesso a recursos padrão.'}
        ]
    )

    # 3. Adiciona a coluna em `users` permitindo NULL
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    
    # 4. Atualiza os usuários existentes para Role=User (ID 3)
    op.execute("UPDATE users SET role_id = 3 WHERE role_id IS NULL")
    
    # 5. Altera a coluna para NOT NULL
    op.alter_column('users', 'role_id', nullable=False)
    
    # 6. Cria a Foreign Key
    op.create_foreign_key('fk_users_role_id_roles', 'users', 'roles', ['role_id'], ['id'])
    
    # 7. Remove o campo antigo array
    op.drop_column('users', 'roles')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
