"""initial_schema

Revision ID: 7addfd20b66b
Revises: 
Create Date: 2026-04-03 10:41:49.438976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7addfd20b66b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drain_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_bueiro', sa.String(length=50), nullable=False),
    sa.Column('distancia_cm', sa.Float(), nullable=False),
    sa.Column('nivel_obstrucao', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('ultima_atualizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sincronizado_rows', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drain_status_id'), 'drain_status', ['id'], unique=False)
    op.create_index(op.f('ix_drain_status_id_bueiro'), 'drain_status', ['id_bueiro'], unique=False)
    op.create_table('home_carousels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('section', sa.Enum('hero', 'alerts', 'stats', name='carousel_section_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_carousels_id'), 'home_carousels', ['id'], unique=False)
    op.create_table('home_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('icon_name', sa.String(), nullable=False),
    sa.Column('color', sa.Enum('success', 'warning', 'danger', name='statcard_color_enum'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_stats_id'), 'home_stats', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_home_stats_id'), table_name='home_stats')
    op.drop_table('home_stats')
    op.drop_index(op.f('ix_home_carousels_id'), table_name='home_carousels')
    op.drop_table('home_carousels')
    op.drop_index(op.f('ix_drain_status_id_bueiro'), table_name='drain_status')
    op.drop_index(op.f('ix_drain_status_id'), table_name='drain_status')
    op.drop_table('drain_status')
    # ### end Alembic commands ###
